[FEATURE] QBank selector button for file/image fields (#2)
* [TASK] Implement extension configuration

Using environment variables with fallback to TYPO3 extension configuration.

* [TASK] Working selector modal

* [TASK] Commented out line 10551 in qbank-connector.js

The line was executing code relating to cropping in global context, which led to an error:

	TypeError: null is not an object (evaluating 'qbankConnectorIframeDocument.contentDocument')
		Eval Code (Anonymous Script 1 (line 3))
		eval
		(anonymous function) (qbank-connector.js:10551)
		globalEval (qbank-connector.js:10552)
		domManip (qbank-connector.js:14715)
		append (qbank-connector.js:14553)
		(anonymous function) (qbank-connector.js:4894)
		(anonymous function) (qbank-connector.js:4826)
		(anonymous function) (qbank-connector.js:12724)
		fire (qbank-connector.js:12579)
		fireWith (qbank-connector.js:12689)
		(anonymous function) (qbank-connector.js:12757)
		(anonymous function) (qbank-connector.js:111)
		(anonymous function) (qbank-connector.js:12724)
		fire (qbank-connector.js:12579)
		fireWith (qbank-connector.js:12689)
		done (qbank-connector.js:17198)
		callback (qbank-connector.js:17508)

* [TASK] Perform download request

* [TASK] Download file from QBank

* [TASK] Add QBank logo icon tx-qbank-logo

* [TASK] Add Extension logo

* [TASK] Prevent selector button from being clicked too early

* [TASK] Validate file extensions before download

* [TASK] Use language labels in JavaScript

* [TASK] Add database fields for status tracking

* [TASK] Write status and QBank ID to sys_file

* [TASK] Allow onload event in qbank-connector.js

In qbank-connector.js the iframe was created and documentContent requested without checking that the iframe was loaded in the DOM. This led to the picker sometimes not being displayed and an error being displayed because `elem.contentDocument || elem.contentWindow.document` returned null in `QBCJQ.content()`.

* [FEATURE] Media usage reporting

* [TASK] Remove GUI base URL

Generated from host instead.

* [TASK] Remove media usage on sys_file_reference delete

* [FEATURE] Optional filtering by deployment site(s)

* [FEATURE] Deployment sites configurable in site and language

* [TASK] Add CI and composer.json magic from ttn/tea extension